{"status": "failed", "name": "run turtlebot3 in a dynamic gazebo world", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "test turtlebot3 navigation"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1633214008109, "historyId": "bf15bd74b3ea08cf65d58741dedda5ed", "start": 1633214008102, "steps": [{"status": "failed", "start": 1633214008103, "stop": 1633214008109, "name": "Then Run rorun for turtlebot3 navigation test", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/meenakshi/anaconda2/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/meenakshi/anaconda2/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/teststeps.py\", line 98, in step_impl\n    assert False\n"}}], "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/meenakshi/anaconda2/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/meenakshi/anaconda2/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/teststeps.py\", line 98, in step_impl\n    assert False\n"}, "uuid": "e06623f1-bb76-4407-8a88-4a73be75929e"}