{"status": "broken", "name": "run turtlebot3 in a static gazebo world cafe", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "test turtlebot3 navigation"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1633547691794, "historyId": "5424f7f1c7cd1fda709bcf7e30640073", "start": 1633547691779, "steps": [{"status": "broken", "start": 1633547691785, "stop": 1633547691793, "name": "Then Finally close all terminals and exit execution", "statusDetails": {"message": "UnboundLocalError: local variable 'subprocess' referenced before assignment\n", "trace": "  File \"/home/meenakshi/anaconda2/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/meenakshi/anaconda2/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/teststeps.py\", line 177, in processkill\n    subprocess = subprocess.Popen(['ps', '-A'], stdout=subprocess.PIPE)\n"}}], "statusDetails": {"message": "UnboundLocalError: local variable 'subprocess' referenced before assignment\n", "trace": "  File \"/home/meenakshi/anaconda2/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/meenakshi/anaconda2/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/teststeps.py\", line 177, in processkill\n    subprocess = subprocess.Popen(['ps', '-A'], stdout=subprocess.PIPE)\n"}, "uuid": "16ad5179-370f-4b06-b506-a0054d98b546"}